# Generated by Django 4.2.4 on 2023-08-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.IntegerField(max_length=10, null=True)),
                ('empdept', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('contact', models.IntegerField(max_length=10, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('join_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
