# Generated by Django 4.1.6 on 2023-08-18 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_comany_name', models.CharField(max_length=255, null=True)),
                ('first_comany_designation', models.CharField(max_length=255, null=True)),
                ('first_comany_duration', models.CharField(max_length=255, null=True)),
                ('first_comany_years', models.CharField(max_length=10, null=True)),
                ('second_comany_name', models.CharField(max_length=255, null=True)),
                ('second_comany_designation', models.CharField(max_length=255, null=True)),
                ('second_comany_duration', models.CharField(max_length=255, null=True)),
                ('second_comany_years', models.CharField(max_length=10, null=True)),
                ('third_comany_name', models.CharField(max_length=255, null=True)),
                ('third_comany_designation', models.CharField(max_length=255, null=True)),
                ('third_comany_duration', models.CharField(max_length=255, null=True)),
                ('third_comany_years', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursepg', models.CharField(max_length=255, null=True)),
                ('schoolpg', models.CharField(max_length=255, null=True)),
                ('yearofpassingpg', models.CharField(max_length=200, null=True)),
                ('percentagepg', models.FloatField(null=True)),
                ('coursegra', models.CharField(max_length=255, null=True)),
                ('schoolgra', models.CharField(max_length=255, null=True)),
                ('yearofpassinggra', models.CharField(max_length=200, null=True)),
                ('percentagegra', models.FloatField(null=True)),
                ('coursessc', models.CharField(max_length=255, null=True)),
                ('schoolssc', models.CharField(max_length=255, null=True)),
                ('yearofpassingssc', models.CharField(max_length=200, null=True)),
                ('percentagessc', models.FloatField(null=True)),
                ('coursehsc', models.CharField(max_length=255, null=True)),
                ('schoolhsc', models.CharField(max_length=255, null=True)),
                ('yearofpassinghsc', models.CharField(max_length=200, null=True)),
                ('percentagehsc', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.IntegerField(null=True)),
                ('empdept', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('join_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
