# Generated by Django 4.1.6 on 2023-08-09 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='yearofpassinhsc',
            new_name='yearofpassinghsc',
        ),
    ]
