# Generated by Django 4.2.5 on 2023-10-04 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='feature_image',
            field=models.ImageField(default=datetime.datetime(2023, 10, 4, 13, 58, 50, 27672, tzinfo=datetime.timezone.utc), upload_to='EMP_images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=datetime.datetime(2023, 10, 4, 13, 59, 0, 755020, tzinfo=datetime.timezone.utc), max_length=1),
            preserve_default=False,
        ),
    ]
