# Generated by Django 4.2.4 on 2023-08-07 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_comany_name', models.CharField(max_length=255, null=True)),
                ('first_comany_designation', models.CharField(max_length=255, null=True)),
                ('first_comany_duration', models.CharField(max_length=255, null=True)),
                ('first_comany_salary', models.IntegerField(null=True)),
                ('second_comany_name', models.CharField(max_length=255, null=True)),
                ('second_comany_designation', models.CharField(max_length=255, null=True)),
                ('second_comany_duration', models.CharField(max_length=255, null=True)),
                ('second_comany_salary', models.IntegerField(null=True)),
                ('third_comany_name', models.CharField(max_length=255, null=True)),
                ('third_comany_designation', models.CharField(max_length=255, null=True)),
                ('third_comany_duration', models.CharField(max_length=255, null=True)),
                ('third_comany_salary', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursepg', models.CharField(max_length=255, null=True)),
                ('schoolpg', models.CharField(max_length=255, null=True)),
                ('yearofpassingpg', models.DateTimeField(null=True)),
                ('percentagepg', models.FloatField(null=True)),
                ('coursegra', models.CharField(max_length=255, null=True)),
                ('schoolgra', models.CharField(max_length=255, null=True)),
                ('yearofpassinggra', models.DateTimeField(null=True)),
                ('percentagegra', models.FloatField(null=True)),
                ('coursessc', models.CharField(max_length=255, null=True)),
                ('schoolssc', models.CharField(max_length=255, null=True)),
                ('yearofpassinssc', models.DateTimeField(null=True)),
                ('percentagessc', models.FloatField(null=True)),
                ('coursehsc', models.CharField(max_length=255, null=True)),
                ('schoolhsc', models.CharField(max_length=255, null=True)),
                ('yearofpassinhsc', models.DateTimeField(null=True)),
                ('percentagehsc', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
