# Generated by Django 4.2.4 on 2023-08-07 05:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_app', '0002_employeeexperience_employeeeducations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeEducations',
            new_name='EmployeeEducation',
        ),
    ]
