# Generated by Django 4.1.6 on 2023-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_rename_yearofpassinhsc_employeeeducation_yearofpassinghsc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='yearofpassinssc',
            new_name='yearofpassingssc',
        ),
    ]
