# Generated by Django 4.1.6 on 2023-08-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_rename_yearofpassinssc_employeeeducation_yearofpassingssc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinggra',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassinghsc',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingpg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='yearofpassingssc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
