# Generated by Django 4.2.5 on 2023-10-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('feature_image', models.ImageField(upload_to='Job_post_images/%Y/%m/%d')),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_active', 'Inactive')], default='active', max_length=20)),
                ('description', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.jobcategory')),
                ('location', models.ManyToManyField(to='web_app.joblocation')),
            ],
        ),
        migrations.CreateModel(
            name='Job_apply_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='Job_apply/resumes/%Y/%m/%d')),
                ('letter', models.FileField(upload_to='Job_apply/letter/%Y/%m/%d')),
                ('quailfation', models.FileField(upload_to='Job_apply/quailfation/%Y/%m/%d')),
                ('apply_date', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.jobcategory')),
                ('location', models.ManyToManyField(to='web_app.joblocation')),
            ],
        ),
    ]
