# Generated by Django 4.1.6 on 2023-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('current_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='Job_apply/resumes/%Y/%m/%d')),
                ('letter', models.FileField(upload_to='Job_apply/letter/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
