# Generated by Django 4.1.6 on 2023-08-20 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_resume_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 20, 8, 20, 25, 300040, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
