# Generated by Django 4.1.6 on 2023-08-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_alter_resume_apply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='apply_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
