# Generated by Django 4.1.6 on 2023-08-20 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_resume_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='quailfation',
            field=models.FileField(default=datetime.datetime(2023, 8, 20, 19, 1, 14, 778300, tzinfo=datetime.timezone.utc), upload_to='Job_apply/quailfation/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
